const sampleProfiles = [
    {
        id: "1",
        name: "Alice Johnson",
        university: "Harvard University",
        studyInterests: ["Physics", "Engineering", "Robotics"],
        currentCourses: ["6.001: Programming", "8.01: Physics I"],
        studyStyle: "Mix of individual work and group problem-solving",
        availability: "Flexible schedule, prefers mornings",
    },
    {
        id: "2",
        name: "Bob Smith",
        university: "Stanford University",
        studyInterests: ["Quantum Mechanics", "Astrophysics", "Mathematics"],
        currentCourses: ["PHYSICS 101: Quantum Theory", "MATH 204: Linear Algebra"],
        studyStyle: "Prefers deep individual research followed by group discussions",
        availability: "Available weekends and evenings",
    },
    {
        id: "3",
        name: "Clara Lee",
        university: "MIT",
        studyInterests: ["Machine Learning", "Data Science", "Artificial Intelligence"],
        currentCourses: ["6.036: Introduction to Machine Learning", "6.041: Probabilistic Systems Analysis"],
        studyStyle: "Enjoys collaborative projects with lots of brainstorming",
        availability: "Available weekday afternoons and evenings",
    },
    {
        id: "4",
        name: "Daniel Kim",
        university: "UC Berkeley",
        studyInterests: ["Economics", "Finance", "Game Theory"],
        currentCourses: ["ECON 101: Macroeconomics", "FINANCE 201: Investment Analysis"],
        studyStyle: "Focuses on theoretical discussions with applied case studies",
        availability: "Prefers afternoons and weekends",
    },
    {
        id: "5",
        name: "Evelyn Green",
        university: "University of Oxford",
        studyInterests: ["Mathematics", "Abstract Algebra", "Topology"],
        currentCourses: ["MATH 301: Abstract Algebra", "MATH 302: Topology"],
        studyStyle: "Independent problem-solving followed by peer review",
        availability: "Flexible, prefers early mornings or late evenings",
    },
    {
        id: "6",
        name: "Michael Tan",
        university: "Princeton University",
        studyInterests: ["Chemistry", "Biochemistry", "Genetics"],
        currentCourses: ["CHEM 210: Organic Chemistry", "BIO 201: Genetics"],
        studyStyle: "Hands-on experiments with group feedback",
        availability: "Weekdays only, prefers afternoons",
    },
    {
        id: "7",
        name: "Sophia Patel",
        university: "University of Cambridge",
        studyInterests: ["Philosophy", "Ethics", "Logic"],
        currentCourses: ["PHIL 101: Ethics", "PHIL 203: Logic and Reasoning"],
        studyStyle: "Enjoys group discussions and debates on philosophical topics",
        availability: "Available weekends and evenings",
    },
    {
        id: "8",
        name: "Liam Wang",
        university: "Caltech",
        studyInterests: ["Computer Science", "Algorithms", "Data Structures"],
        currentCourses: ["CS 101: Data Structures", "CS 203: Algorithms"],
        studyStyle: "Focuses on hands-on coding and pair programming",
        availability: "Weekends only, prefers afternoons",
    },
    {
        id: "9",
        name: "Emma Thompson",
        university: "Columbia University",
        studyInterests: ["Sociology", "Psychology", "Human Behavior"],
        currentCourses: ["SOC 101: Introduction to Sociology", "PSYCH 201: Cognitive Psychology"],
        studyStyle: "Likes open-ended discussions with peer feedback",
        availability: "Flexible, available most evenings",
    },
    {
        id: "10",
        name: "Noah Wilson",
        university: "University of Toronto",
        studyInterests: ["Environmental Science", "Ecology", "Climate Change"],
        currentCourses: ["ENV 101: Introduction to Ecology", "CLIM 203: Climate Science"],
        studyStyle: "Enjoys field research with data analysis and group presentations",
        availability: "Available weekdays and weekends",
    },
];

export default sampleProfiles;